apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: transmit-policy
spec:
  podSelector:
    matchLabels:
      task: transmit
  ingress:
    - from:
      - podSelector:
          matchExpressions:
            - {key: task, operator: In, values: [transmit, analyze_transmit, command_transmit, all]}
  egress:
    - to:
      - podSelector:
          matchExpressions:
            - {key: task, operator: In, values: [transmit, analyze_transmit, command_transmit, all]}

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: analyze-policy
spec:
  podSelector:
    matchLabels:
      task: analyze
  ingress:
    - from:
      - podSelector:
          matchExpressions:
            - {key: task, operator: In, values: [analyze, analyze_transmit, analyze_preprocess, all]}
  egress:
    - to:
      - podSelector:
          matchExpressions:
            - {key: task, operator: In, values: [analyze, analyze_transmit, analyze_preprocess, all]}
---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: command-policy
spec:
  podSelector:
    matchLabels:
      task: command
  ingress:
    - from:
      - podSelector:
          matchExpressions:
            - {key: task, operator: In, values: [command, command_transmit, command_preprocess, all]}
  egress:
    - to:
      - podSelector:
          matchExpressions:
            - {key: task, operator: In, values: [command, command_transmit, command_preprocess, all]}

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: preprocess-policy
spec:
  podSelector:
    matchLabels:
      task: preprocess
  ingress:
    - from:
      - podSelector:
          matchExpressions:
            - {key: task, operator: In, values: [preprocess, analyze_preprocess, command_preprocess, all]}
  egress:
    - to:
      - podSelector:
          matchExpressions:
            - {key: task, operator: In, values: [preprocess, analyze_preprocess, command_preprocess, all]}

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: at-policy
spec:
  podSelector:
    matchLabels:
      task: analyze_transmit
  ingress:
    - from:
      - podSelector:
          matchExpressions:
            - {key: task, operator: In, values: [transmit, analyze, analyze_transmit, analyze_preprocess, command_transmit, all]}
  egress:
    - to:
      - podSelector:
          matchExpressions:
            - {key: task, operator: In, values: [transmit, analyze, analyze_transmit, analyze_preprocess, command_transmit, all]}

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ap-policy
spec:
  podSelector:
    matchLabels:
      task: analyze_preprocess
  ingress:
    - from:
      - podSelector:
          matchExpressions:
            - {key: task, operator: In, values: [analyze, preprocess, analyze_transmit, analyze_preprocess, command_preprocess, all]}
  egress:
    - to:
      - podSelector:
          matchExpressions:
            - {key: task, operator: In, values: [analyze, preprocess, analyze_transmit, analyze_preprocess, command_preprocess, all]}

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ct-policy
spec:
  podSelector:
    matchLabels:
      task: command_transmit
  ingress:
    - from:
      - podSelector:
          matchExpressions:
            - {key: task, operator: In, values: [command, transmit, command_transmit, analyze_transmit, command_preprocess, all]}
  egress:
    - to:
      - podSelector:
          matchExpressions:
            - {key: task, operator: In, values: [command, transmit, command_transmit, analyze_transmit, command_preprocess, all]}

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cp-policy
spec:
  podSelector:
    matchLabels:
      task: command_preprocess
  ingress:
    - from:
      - podSelector:
          matchExpressions:
            - {key: task, operator: In, values: [preprocess, command, command_preprocess, analyze_preprocess, command_transmit, all]}
  egress:
    - to:
      - podSelector:
          matchExpressions:
            - {key: task, operator: In, values: [preprocess, command, command_preprocess, analyze_preprocess, command_transmit, all]}

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: global-policy
spec:
  podSelector:
    matchLabels:
      task: all
  ingress:
    - from:
      - podSelector:
          matchExpressions:
            - {key: task, operator: In, values: [preprocess, command, analyze, transmit, analyze_transmit, command_preprocess, analyze_preprocess, command_transmit, all]}
  egress:
    - to:
      - podSelector:
          matchExpressions:
            - {key: task, operator: In, values: [preprocess, command, analyze, transmit, analyze_transmit, command_preprocess, analyze_preprocess, command_transmit, all]}

---
