apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-drone1-to-drone3
spec:
  podSelector:
    matchLabels:
      app: droneservice
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            name: drone1service1
  egress:
    - to:
      - podSelector:
          matchLabels:
            name: drone3service1
