apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sensor-data-policy
spec:
  podSelector:
    matchLabels:
      sensor-data: allowed
  ingress:
    - from:
        - podSelector:
              matchLabels:
                sensor-data: allowed
        - podSelector:
              matchLabels:
                all: allowed    
      ports:
        - protocol: TCP
          port: 5002
  egress:
    - to:
        - podSelector:
              matchLabels:
                sensor-data: allowed
        - podSelector:
              matchLabels:
                all: allowed  
      ports:
        - protocol: TCP
          port: 5002

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: position-data-policy
spec:
  podSelector:
    matchLabels:
      position-data: allowed
  ingress:
    - from:
        - podSelector:
            matchLabels:
              position-data: allowed
        - podSelector:
            matchLabels:
              all: allowed    
      ports:
        - protocol: UDP
          port: 53
  egress:
    - to:
        - podSelector:
              matchLabels:
                position-data: allowed
        - podSelector:
              matchLabels:
                all: allowed       
      ports:
        - protocol: UDP
          port: 53
---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: command-policy
spec:
  podSelector:
    matchLabels:
      command: allowed
  ingress:
    - from:
        - podSelector:
              matchLabels:
                command: allowed
        - podSelector:
              matchLabels:
                all: allowed    
      ports:
        - protocol: TCP
          port: 5001
  egress:
    - to:
        - podSelector:
              matchLabels:
                command: allowed
        - podSelector:
              matchLabels:
                all: allowed  
      ports:
        - protocol: TCP
          port: 5001

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: video-data-policy
spec:
  podSelector:
    matchLabels:
      video-data: allowed
  ingress:
    - from:
      - podSelector:
            matchLabels:
              video-data: allowed
      - podSelector:
            matchLabels:
              all: allowed    
        ports:
          - protocol: UDP
            port: 67
  egress:
    - to:
      - podSelector:
            matchLabels:
              video-data: allowed
      - podSelector:
            matchLabels:
              all: allowed
        ports:
          - protocol: UDP
            port: 67

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: global-policy
spec:
  podSelector:
    matchLabels:
      video-data: allowed
  ingress:
    - from:
      - podSelector:
            matchLabels:
              position-data: allowed
      - podSelector:
            matchLabels:
              sensor-data: allowed   
      - podSelector:
            matchLabels:
              command: allowed
      - podSelector:
            matchLabels:
              video-data: allowed
      - podSelector:
            matchLabels:
              all: allowed    
  egress:
    - to:
      - podSelector:
            matchLabels:
              position-data: allowed
      - podSelector:
            matchLabels:
              sensor-data: allowed   
      - podSelector:
            matchLabels:
              command: allowed
      - podSelector:
            matchLabels:
              video-data: allowed
      - podSelector:
            matchLabels:
              all: allowed
---
