apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: transmit_policy
spec:
  podSelector:
    matchLabels:
      task: transmit
  ingress:
    - from:
      - podSelector:
          matchExpressions:
            - {key: task, operator: In, values: [transmit, analyze_transmit, command_transmit, all]}
  egress:
    - to:
      - podSelector:
          matchExpressions:
            - {key: task, operator: In, values: [transmit, analyze_transmit, command_transmit, all]}

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: analyze_policy
spec:
  podSelector:
    matchExpressions:
      - {key: task, operator: In, values: [analyze, analyze_transmit, analyze_preprocess, all]}
  ingress:
    - from:
      - podSelector:
          matchExpressions:
            - {key: task, operator: In, values: [analyze, analyze_transmit, analyze_preprocess, all]}
  egress:
    - to:
      - podSelector:
          matchExpressions:
            - {key: task, operator: In, values: [analyze, analyze_transmit, analyze_preprocess, all]}
---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: command_policy
spec:
  podSelector:
    matchExpressions:
      - {key: task, operator: In, values: [command, command_transmit, command_preprocess, all]}
  ingress:
    - from:
      - podSelector:
          matchExpressions:
            - {key: task, operator: In, values: [command, command_transmit, command_preprocess, all]}
  egress:
    - to:
      - podSelector:
          matchExpressions:
            - {key: task, operator: In, values: [command, command_transmit, command_preprocess, all]}

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: preprocess_policy
spec:
  podSelector:
    matchExpressions:
      - {key: task, operator: In, values: [preprocess, analyze_preprocess, command_preprocess, all]}
  ingress:
    - from:
      - podSelector:
          matchExpressions:
            - {key: task, operator: In, values: [preprocess, analyze_preprocess, command_preprocess, all]}
  egress:
    - to:
      - podSelector:
          matchExpressions:
            - {key: task, operator: In, values: [preprocess, analyze_preprocess, command_preprocess, all]}

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: at_policy
spec:
  podSelector:
    matchExpressions:
      - {key: task, operator: In, values: [analyze_transmit]}
  ingress:
    - from:
      - podSelector:
          matchExpressions:
            - {key: task, operator: In, values: [transmit, analyze, analyze_transmit, analyze_preprocess, command_transmit, all]}
  egress:
    - to:
      - podSelector:
          matchExpressions:
            - {key: task, operator: In, values: [transmit, analyze, analyze_transmit, analyze_preprocess, command_transmit, all]}

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ap_policy
spec:
  podSelector:
    matchExpressions:
      - {key: task, operator: In, values: [analyze_preprocess]}
  ingress:
    - from:
      - podSelector:
          matchExpressions:
            - {key: task, operator: In, values: [analyze, preprocess, analyze_transmit, analyze_preprocess, command_preprocess, all]}
  egress:
    - to:
      - podSelector:
          matchExpressions:
            - {key: task, operator: In, values: [analyze, preprocess, analyze_transmit, analyze_preprocess, command_preprocess, all]}

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ct_policy
spec:
  podSelector:
    matchLabels:
      name: command_transmit
  ingress:
    - from:
      - podSelector:
          matchExpressions:
            - {key: task, operator: In, values: [command, transmit, command_transmit, analyze_transmit, command_preprocess, all]}
  egress:
    - to:
      - podSelector:
          matchExpressions:
            - {key: task, operator: In, values: [command, transmit, command_transmit, analyze_transmit, command_preprocess, all]}

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cp_policy
spec:
  podSelector:
    matchExpressions:
      - {key: name, operator: In, values: [command_preprocess]}
  ingress:
    - from:
      - podSelector:
          matchExpressions:
            - {key: task, operator: In, values: [preprocess, command, command_preprocess, analyze_preprocess, command_transmit, all]}
  egress:
    - to:
      - podSelector:
          matchExpressions:
            - {key: task, operator: In, values: [preprocess, command, command_preprocess, analyze_preprocess, command_transmit, all]}

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: global_policy
spec:
  podSelector:
    matchExpressions:
      - {key: name, operator: In, values: [all]}
  ingress:
    - from:
      - podSelector:
          matchExpressions:
            - {key: task, operator: In, values: [preprocess, command, analyze, transmit, analyze_transmit, command_preprocess, analyze_preprocess, command_transmit, all]}
  egress:
    - to:
      - podSelector:
          matchExpressions:
            - {key: task, operator: In, values: [preprocess, command, analyze, transmit, analyze_transmit, command_preprocess, analyze_preprocess, command_transmit, all]}

---
