apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: transmit-policy
spec:
  podSelector:
    matchLabels:
      transmit: allowed
  ingress:
    - from:
      - podSelector:
            matchLabels:
              transmit: allowed
        ports:
          - protocol: TCP
      - podSelector:
            matchLabels:
              all: allowed    
  egress:
      - podSelector:
            matchLabels:
              transmit: allowed
        ports:
          - protocol: TCP
      - podSelector:
            matchLabels:
              all: allowed  

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: analyze-policy
spec:
  podSelector:
    matchLabels:
      analyze: allowed
  ingress:
    - from:
      - podSelector:
            matchLabels:
              analyze: allowed
      - podSelector:
            matchLabels:
              all: allowed              
  egress:
    - to:
      - podSelector:
            matchLabels:
              analyze: allowed
      - podSelector:
            matchLabels:
              all: allowed         
---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: command-policy
spec:
  podSelector:
    matchLabels:
      command: allowed
  ingress:
    - from:
      - podSelector:
            matchLabels:
              command: allowed
        ports:
          - protocol: ICMP
      - podSelector:
            matchLabels:
              all: allowed    
  egress:
    - to:
      - podSelector:
            matchLabels:
              command: allowed
        ports:
          - protocol: ICMP
      - podSelector:
            matchLabels:
              all: allowed  

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: preprocess-policy
spec:
  podSelector:
    matchLabels:
      preprocess: allowed
  ingress:
    - from:
      - podSelector:
            matchLabels:
              preprocess: allowed
      - podSelector:
            matchLabels:
              all: allowed    
  egress:
    - to:
      - podSelector:
            matchLabels:
              preprocess: allowed
      - podSelector:
            matchLabels:
              all: allowed  

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: global-policy
spec:
  podSelector:
    matchLabels:
      preprocess: allowed
  ingress:
    - from:
      - podSelector:
            matchLabels:
              analyze: allowed
      - podSelector:
            matchLabels:
              transmit: allowed   
      - podSelector:
            matchLabels:
              command: allowed
      - podSelector:
            matchLabels:
              preprocess: allowed
      - podSelector:
            matchLabels:
              all: allowed    
  egress:
    - to:
      - podSelector:
            matchLabels:
              analyze: allowed
      - podSelector:
            matchLabels:
              transmit: allowed   
      - podSelector:
            matchLabels:
              command: allowed
      - podSelector:
            matchLabels:
              preprocess: allowed
      - podSelector:
            matchLabels:
              all: allowed
---
