apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: transmit_policy
spec:
  podSelector:
    matchLabels:
      task: transmit
  ingress:
    - from:
      - podSelector:
          matchLabels:
            task: 
            - transmit
            - analyze_transmit
            - command_transmit
            - all
  egress:
    - to:
      - podSelector:
          matchLabels:
            task: 
            - transmit
            - analyze_transmit
            - command_transmit
            - all

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: analyze_policy
spec:
  podSelector:
    matchLabels:
      task: analyze
  ingress:
    - from:
      - podSelector:
          matchLabels:
            task: 
            - analyze
            - analyze_transmit
            - analyze_preprocess
            - all
  egress:
    - to:
      - podSelector:
          matchLabels:
            task: 
            - analyze
            - analyze_transmit
            - analyze_preprocess
            - all
---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: command_policy
spec:
  podSelector:
    matchLabels:
      task: command
  ingress:
    - from:
      - podSelector:
          matchLabels:
            task: 
            - command
            - command_transmit
            - command_preprocess
            - all
  egress:
    - to:
      - podSelector:
          matchLabels:
            task: 
            - command
            - command_transmit
            - command_preprocess
            - all
---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: preprocess_policy
spec:
  podSelector:
    matchLabels:
      task: preprocess
  ingress:
    - from:
      - podSelector:
          matchLabels:
            task: 
            - preprocess
            - analyze_preprocess
            - command_preprocess
            - all
  egress:
    - to:
      - podSelector:
          matchLabels:
            task: 
            - preprocess
            - analyze_preprocess
            - command_preprocess
            - all
---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: at_policy
spec:
  podSelector:
    matchLabels:
      task: analyze_transmit
  ingress:
    - from:
      - podSelector:
          matchLabels:
            task: 
            - transmit
            - analyze
            - analyze_transmit
            - analyze_preprocess
            - command_transmit
            - all
  egress:
    - to:
      - podSelector:
          matchLabels:
            task: 
            - transmit
            - analyze
            - analyze_transmit
            - analyze_preprocess
            - command_transmit
            - all
---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ap_policy
spec:
  podSelector:
    matchLabels:
      task: analyze_preprocess
  ingress:
    - from:
      - podSelector:
          matchLabels:
            task: 
            - analyze
            - preprocess
            - analyze_transmit
            - analyze_preprocess
            - command_preprocess
            - all
  egress:
    - to:
      - podSelector:
          matchLabels:
            task: 
            - analyze
            - preprocess
            - analyze_transmit
            - analyze_preprocess
            - command_preprocess
            - all
---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ct_policy
spec:
  podSelector:
    matchLabels:
      name: command_transmit
  ingress:
    - from:
      - podSelector:
          matchLabels:
            task: 
            - command
            - transmit
            - command_transmit
            - analyze_transmit
            - command_preprocess
            - all
  egress:
    - to:
      - podSelector:
          matchLabels:
            task: 
            - command
            - transmit
            - command_transmit
            - analyze_transmit
            - command_preprocess
            - all
---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cp_policy
spec:
  podSelector:
    matchLabels:
      name: command_preprocess
  ingress:
    - from:
      - podSelector:
          matchLabels:
            task: 
            - preprocess
            - command
            - command_preprocess
            - analyze_preprocess
            - command_transmit
            - all
  egress:
    - to:
      - podSelector:
          matchLabels:
            task: 
            - preprocess
            - command
            - command_preprocess
            - analyze_preprocess
            - command_transmit
            - all
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: global_policy
spec:
  podSelector:
    matchLabels:
      name: all
  ingress:
    - from:
      - podSelector:
          matchLabels:
            task: 
            - preprocess
            - command
            - analyze
            - transmit
            - analyze_transmit
            - command_preprocess
            - command_preprocess
            - analyze_preprocess
            - command_transmit
            - all
  egress:
    - to:
      - podSelector:
          matchLabels:
            task: 
            - preprocess
            - command
            - analyze
            - transmit
            - analyze_transmit
            - command_preprocess
            - command_preprocess
            - analyze_preprocess
            - command_transmit
            - all
---
