global:
  scrape_interval: 15s

scrape_configs:
- job_name: 'k3s-metrics'
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_label_app]
    separator: ;
    regex: your-app-label
    replacement: $1
    action: keep
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets: ['kubernetes.default.svc:443']
